dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('df_goods.urls')),
    url(r'^user/', include('df_user.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^cart/', include('df_cart.urls')),
    url(r'^order/', include('df_order.urls')),
    # url(r'^search/', include('haystack.urls')),

]

dailyfresh/df_cart/urls.py
from django.conf.urls import url
import views

urlpatterns = [
	url(r'^$', views.cart, name='cart'),
	url(r'^add(\d+)_(\d+)/$', views.add, name='add'),
	url(r'^edit(\d+)_(\d+)/$', views.edit, name='edit'),
	url(r'^delete(\d+)/$', views.delete, name='delete'),

]

dailyfresh/df_user/urls.py
from django.conf.urls import url
import views

urlpatterns = [
	url(r'^register/$', views.register, name='register'),
	url(r'^register_handle/$', views.register_handle, name='register_handle'),
	url(r'^login/$', views.login, name='login'),	
	url(r'^login_handle/$', views.login_handle, name='login_handle'),
	url(r'^register_exist/$', views.register_exist, name='register_exist'),
	url(r'^info/$', views.info, name='info'),
	url(r'^order(\d*)/$', views.order, name='order'),
	url(r'^site/$', views.site, name='site'),
	url(r'^logout/$', views.logout, name='logout'),
	
]

dailyfresh/df_order/models.py
from django.db import models

# Create your models here.

import sys
default_encoding = "utf-8"
if sys.getdefaultencoding() != default_encoding:
	reload(sys)
	sys.setdefaultencoding(default_encoding)


class Order_info(models.Model):
	oid = models.CharField(max_length=20, primary_key=True)
	user =models.ForeignKey('df_user.User_info')
	ocreat_date =models.DateTimeField(auto_now_add=True)
	omodified_date =models.DateTimeField(auto_now=True)
	ois_pay =models.CharField(max_length=3, null=True,blank=True)
	ototal =models.DecimalField(max_digits=8,decimal_places=2,null=True,blank=True)
	oaddress =models.CharField(max_length=150, null=True,blank=True)
	oback1 = models.CharField(max_length=100, null=True,blank=True)
	class Meta():
		db_table = 'order_info'

	def __str__(self):
		return self.oid


class Order_detail_info(models.Model):
	order = models.ForeignKey('Order_info')
	goods = models.ForeignKey('df_goods.Goods_info')
	price_fina = models.DecimalField(max_digits=6,decimal_places=2,null=True,blank=True)
	count = models.IntegerField(null=True)
	trans_states = models.CharField(max_length=100, null=True,blank=True)

	class Meta():
		db_table = 'order_detail'

	def __str__(self):
		return self.order_id

dailyfresh/df_user/models.py
from django.db import models

# Create your models here.
import sys
default_encoding = "utf-8"
if sys.getdefaultencoding() != default_encoding:
	reload(sys)
	sys.setdefaultencoding(default_encoding)

class User_info(models.Model):
	"""en"""
	uname = models.CharField(max_length=20)
	upwd = models.CharField(max_length=40)
	uemail = models.CharField(max_length=30, blank=True)
	ureceive = models.CharField(max_length=50, null=True,)
	uaddress = models.CharField(max_length=100, null=True,)
	upost = models.CharField(max_length=6, blank=True, null=True)
	uphone = models.CharField(max_length=14, null=True,)
	isdelete = models.BooleanField(default=False)
	udate_time = models.DateTimeField(blank=True)
	utest1 = models.CharField(max_length=100, null=True,)
	class Meta():
		db_table = "dailyfresh_table"

	def __str__(self):
		return self.uname.encode('utf-8')

dailyfresh/df_user/views.py
# coding=utf-8
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from hashlib import sha1
from models import *
from datetime import *
from django.core.paginator import Paginator,Page

from . import user_decorator
# import user_decorator
from df_user.models import *
from df_goods.models import *
from df_order.models import *

# Create your views here.

def register(request):
	return render(request, "df_user/register.html")

def register_handle(request):
	post = request.POST
	uname = post.get('user_name')
	upwd = post.get('pwd')
	ucpwd = post.get('cpwd')
	uemail = post.get('email')

	if upwd != ucpwd:
		return redirect('/user/register/')

	s1 =sha1()
	s1.update(upwd)
	upwd_sha1 = s1.hexdigest()

	user = User_info()
	user.uname = uname
	user.upwd = upwd_sha1
	user.uemail = uemail
	user.isdelete = 0
	user.udate_time = datetime.now()
	user.save()

	return redirect('/user/login/')

def register_exist(request):
	uname = request.GET.get('uname')
	count = User_info.objects.filter(uname=uname).count()
	context = {'count': count}
	return JsonResponse(context)

def login(request):
	uname = request.COOKIES.get('uname', '')
	context = {'error_name':0, 'error_pwd':0, 'uname':uname, 'upwd':'',}
	return render(request, 'df_user/login.html', context)

def logout(request):
	request.session.flush()
	return redirect('/')

def login_handle(request):
	post = request.POST
	uname = post.get('username')
	upwd = post.get('pwd')
	ureme_name = post.get('reme_name', 0)

	user = User_info.objects.filter(uname=uname)
	length = len(user)  # [] or [{},]

	if length==1:
		s1 = sha1()
		s1.update(upwd)
		upwd_tem = s1.hexdigest()

		if user[0].upwd == upwd_tem:
			url = request.COOKIES.get('url', '/')
			rend = HttpResponseRedirect(url)
			# 记住用户名
			if ureme_name != 0:
				rend.set_cookie('uname', uname)
			else:
				rend.set_cookie('uname', '', max_age=-1) 
				#cookie值为空，-1是立即过期

			request.session['user_id'] = user[0].id
			request.session['user_name'] = user[0].uname
			#将用户id和用户名存在session数据表中,默认两周后过期删除

			return rend
		else:
			context = {'error_name':0, 'error_pwd':1, 'uname':uname, 'upwd':upwd, }
			return render(request, 'df_user/login.html', context)
	else:
		context = {'error_name':1, 'error_pwd':0, 'uname':uname, 'upwd':upwd, }
		return render(request, 'df_user/login.html', context)

@user_decorator.login
def info(request):
	user = User_info.objects.get(id=request.session['user_id'],)
	#最近浏览产品
	goods_ids = request.COOKIES.get('goods_ids', '')
	if goods_ids != '':
		goods_ids_tem = goods_ids.split(',')
		goods_list = []
		# Goods_info.objects.filter(id__in=goods_ids_tem) 
		# 字段查询，选出在列表中id的对象集
		for gid in goods_ids_tem:
			goods_list.append(Goods_info.objects.get(id=int(gid)))
	else:
		goods_list = Goods_info.objects.all().order_by('-id')[0:5]

	if user:
		user_email = user.uemail
		user_address = user.uaddress
		context = { 'uname':request.session['user_name'], 
					'uemail':user_email, 
					'uaddress':user_address,
					'goods_list':goods_list, }
		return render(request, 'df_user/user_center_info.html', context)
	else:
		return redirect('/user/login/')

@user_decorator.login
def order(request, pindex):
	if pindex == '':
		pindex = '1'

	order_list = Order_info.objects.filter(user_id=request.session['user_id']).order_by('-oid')
	paginator_page = Paginator(order_list,2)
	page_num = paginator_page.page(int(pindex))

	context = {'uname':request.session['user_name'],
				'paginator_page':paginator_page, 
				'page_num':page_num, }
	return render(request, 'df_user/user_center_order.html', context)

@user_decorator.login
def site(request):
	user = User_info.objects.get(id=request.session['user_id'])
	if request.method=='POST':
		post = request.POST
		user.ureceive = post.get('ureceive')
		user.uaddress = post.get('uaddress')
		user.upost = post.get('upost')
		user.uphone = post.get('uphone')
		user.save()
	cur_address = str(user.uaddress) +" &nbsp;(" + str(user.ureceive) + ') <收> &nbsp; ' + str(user.uphone)
	context = {'user':user, 'cur_address':cur_address, }
	return render(request, 'df_user/user_center_site.html', context )

dailyfresh/templates/df_user/login.html
{% extends 'base_footer.html' %}

{% block head_title %}
用户登录
{% endblock head_title %}

{% block head_js %}
<script type="text/javascript">
	$(function(){
		name_error = false;
		pwd_error = false;

		if ({{error_name}}==1){
			$('.user_error').html('用户名错误').show()
		}

		if ({{error_pwd}}==1){
			$('.pwd_error').html('密码错误').show()
		}

		$('.name_input').blur(function () {
			var len = $('.name_input').val().length;
			if(len<5||len>20){
				$('.user_error').html('请输入5-20个字符的用户名').show()
				name_error = true;
			}
			else{
				$('.user_error').hide();
				name_error = false;
			}
		});

		$('.pass_input').blur(function(){
			var len = $('.pass_input').val().length;
			if(len<8||len>20){
				$('.pwd_error').html('密码最少8位，最长20位').show()
				pwd_error = true;
			}
			else{
				$('.pwd_error').hide();
				pwd_error = false;
			}		
		});

		$('.form_input').submit(function(){
			if(name_error == false && pwd_error == false){
				return true;
			}
			else{
				return false;
			}
		});

	});
</script>
{% endblock head_js %}

{% block body_content %}
<div class="login_top clearfix">
	<a href="/" class="login_logo"><img src="/static/df_user/images/logo02.png"></a>	
</div>

<div class="login_form_bg">
	<div class="login_form_wrap clearfix">
		<div class="login_banner fl"></div>
		<div class="slogan fl">日夜兼程 · 急速送达</div>
		<div class="login_form fr">
			<div class="login_title clearfix">
				<h1>用户登录</h1>
				<a href="/user/register/" title="点击注册">立即注册</a>
			</div>
			<div class="form_input">
				<form action="/user/login_handle/" method="post">
					{% csrf_token %}
					<input type="text" name="username" value='{{uname}}' class="name_input" placeholder="请输入用户名">
					<div class="user_error">输入错误</div>
					<input type="password" name="pwd" value="{{upwd}}" class="pass_input" placeholder="请输入密码">
					<div class="pwd_error">输入错误</div>
					<div class="more_input clearfix">
						<input type="checkbox" name="reme_name" value="1" checked="checked">
						<label>记住用户名</label>
						<a href="#">忘记密码</a>
					</div>
					<input type="submit" value="登录" class="input_submit">
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock body_content %}


dailyfresh/templates/df_user/register.html
{% extends 'base_footer.html' %}

{% block head_title %}
用户注册
{% endblock head_title %}

{% block head_js %}
<script type="text/javascript" src="/static/df_user/js/register.js"></script>
{% endblock head_js %}

{% block body_content %}
<div class="register_con">
	<div class="l_con fl">
		<a class="reg_logo" href="/"><img src="/static/df_user/images/logo02.png"></a>
		<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
		<div class="reg_banner"></div>
	</div>

	<div class="r_con fr">
		<div class="reg_title clearfix">
			<h1>用户注册</h1>
			<a href="/user/login/" title="点击登录">登录</a>
		</div>
		<div class="reg_form clearfix">
			<form action="/user/register_handle/" method="post">
			{% csrf_token %}
			<ul>
				<li>
					<label>用户名:</label>
					<input type="text" name="user_name" id="user_name">
					<span class="error_tip">提示信息</span>
				</li>					
				<li>
					<label>密码:</label>
					<input type="password" name="pwd" id="pwd">
					<span class="error_tip">提示信息</span>
				</li>
				<li>
					<label>确认密码:</label>
					<input type="password" name="cpwd" id="cpwd">
					<span class="error_tip">提示信息</span>
				</li>
				<li>
					<label>邮箱:</label>
					<input type="text" name="email" id="email">
					<span class="error_tip">提示信息</span>
				</li>
				<li class="agreement">
					<input type="checkbox" name="allow" id="allow" checked="checked">
					<label>同意”天天生鲜用户使用协议“</label>
					<span class="error_tip2">提示信息</span>
				</li>
				<li class="reg_sub">
					<input type="submit" value="注 册" name="">
				</li>
			</ul>				
			</form>
		</div>

	</div>

</div>
{% endblock body_content %}


dailyfresh/templates/df_user/user_center_info.html
{% extends 'base_user_center.html' %}

{% block head_title %}
用户中心
{% endblock head_title %}

{% block head_uname %}
{{uname}}
{% endblock head_uname %}

{% block body_right_content %}
<div class="right_content clearfix">
		<div class="info_con clearfix">
		<h3 class="common_title2">基本信息</h3>
				<ul class="user_info_list">
					<li><span>用户名：</span>{{uname}}</li>
					<li><span>联系方式：</span>{{uemail}}</li>
					<li><span>联系地址：</span>{{uaddress}}</li>			
				</ul>
		</div>
		
		<h3 class="common_title2">最近浏览</h3>
		<div class="has_view_list">
			<ul class="goods_type_list clearfix">
			{% for g in goods_list %}
		<li>
			<a href="/{{g.id}}/"><img src="/static/{{g.gpic}}"></a>
			<h4><a href="/{{g.id}}/">
			{% if g.gtitle|length < 9 %}
			{{g.gtitle}}
			{% else %}
			{{g.gtitle|slice:'8'}}...
			{% endif %}
			</a></h4>
			<div class="operate">
				<span class="prize">￥{{g.gprice}}</span>
				<span class="unit">{{g.gprice}}/{{g.gunit}}</span>
				<a href="#" class="add_goods" title="加入购物车"></a>
			</div>
		</li>
			{% endfor %}
	
			</ul>
		</div>
</div>
{% endblock body_right_content %}


dailyfresh/templates/df_user/user_center_order.html
{% extends 'base_user_center.html' %}

{% block head_title %}
用户中心
{% endblock head_title %}

{% block head_uname %}
{{uname}}
{% endblock head_uname %}

{% block head_js %}
<script type="text/javascript">
$(function(){
	$('.col04').each(function () {
		num=parseFloat($(this).prev().text())
		price=parseFloat($(this).prev().prev().find('span').text())
		$(this).text((num*price).toFixed(2)+'元')
  });

  $('.list li').eq(1).children('a').addClass('active').parent().siblings().children('a').removeClass('active');

});
</script>
{% endblock head_js %}

{% block body_right_content %}
<div class="right_content clearfix">
		<h3 class="common_title2">全部订单</h3>

		{% for order_tem in page_num %}
		<ul class="order_list_th w978 clearfix">
			<li class="col01">{{order_tem.omodified_date}}</li>
			<li class="col02">订单号：{{order_tem.oid}}</li>
			<li class="col02 stress">
			{% if order_tem.ois_pay|default:'0' == '0' %}
			未支付
			{% elif order_tem.ois_pay|default:'0' == '1' %}
			已支付
			{% else %}
			未支付
			{% endif %}
			</li>
			<li class="col02">快递:10元</li>
		</ul>
		<table class="order_list_table w980">
			<tbody>
				<tr>
					<td width="55%">
						{% for detail_tem in order_tem.order_detail_info_set.all %}
						<ul class="order_goods_list clearfix">					
							<li class="col01"><img src="/static/{{detail_tem.goods.gpic}}"></li>
							<li class="col02">
							{% if detail_tem.goods.gtitle|length < 7 %}
							{{detail_tem.goods.gtitle}}
							{% else %}
							{{detail_tem.goods.gtitle|slice:'6'}}...
							{% endif %}
							<em><span>{{detail_tem.price_fina}}</span>元/{{detail_tem.goods.gunit}}</em>
							</li>	
							<li class="col03">{{detail_tem.count}}</li>
							<li class="col04">0元</li>	
						</ul>
						{% endfor %}

					</td>
					<td width="15%">{{order_tem.ototal}}元</td>
					{% if order_tem.ois_pay|default:'0' = '0' %}
					<td width="15%">待付款</td>
					<td width="15%"><a href="/order/pay{{order_tem.oid}}/" class="oper_btn">去付款</a></td>
					{% elif order_tem.ois_pay|default:'0' = '1' %}
					<td width="15%">已付款</td>
					<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
					{% else %}
					<td width="15%">待付款</td>
					<td width="15%"><a href="/order/pay{{order_tem.oid}}/" class="oper_btn">去付款</a></td>
					{% endif %}
				</tr>
			</tbody>
		</table>
		{% endfor %}

		<div class="pagenation">
			{% if page_num.has_previous %}
			<a href="/user/order{{page_num.previous_page_number}}/"><上一页</a>
			{% endif %}

			{% for pa in paginator_page.page_range %}
			{% if pa == page_num.number %}
			<!-- <a href="javascript:;" class="active">{{pa}}</a> -->
			<a href="#" class="active" onclick="return false">{{pa}}</a>
			{% else %}
			<a href="/user/order{{pa}}/">{{pa}}</a>
			{% endif %}
			{% endfor %}

			{% if page_num.has_next %}
			<a href="/user/order{{page_num.next_page_number}}/"><下一页</a>
			{% endif %}
		</div>
</div>
</div>
{% endblock body_right_content %}

dailyfresh/templates/df_user/user_center_site.html
{% extends 'base_user_center.html' %}

{% block head_title %}
用户中心
{% endblock head_title %}

{% block head_uname %}
{{user.uname}}
{% endblock head_uname %}

{% block head_js %}
<script type="text/javascript">
	$(function(){
		$('.list li').eq(2).children('a').addClass('active').parent().siblings().children('a').removeClass('active');
	});
</script>
{% endblock head_js %}

{% block body_right_content %}
<div class="right_content clearfix">
		<h3 class="common_title2">收货地址</h3>
		<div class="site_con">
			<dl>
				<dt>当前地址：</dt>
				<dd>{{cur_address|safe}}</dd>
			</dl>					
		</div>
		<h3 class="common_title2">编辑地址</h3>
		<div class="site_con">
			<form action="/user/site/" method="post">
				{% csrf_token %}
				<div class="form_group">
					<label>收件人：</label>
					<input type="text" name="ureceive" value="{{user.ureceive}}">
				</div>
				<div class="form_group form_group2">
					<label>详细地址：</label>
					<textarea class="site_area" name="uaddress">{{user.uaddress}}</textarea>
				</div>
				<div class="form_group">
					<label>邮编：</label>
					<input type="text" name="upost" value="{{user.upost}}">
				</div>
				<div class="form_group">
					<label>手机：</label>
					<input type="text" name="uphone" value="{{user.uphone}}">
				</div>

				<input type="submit" value="添加" class="info_submit">
			</form>
		</div>
</div>
</div>
{% endblock body_right_content %}